name: main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node and yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: |
          echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/.yarn/install-state.gz
          key: ${{ runner.os }}-yarnNodeModules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build all
        run: yarn run build 

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: npx semantic-release